services:
  mysql-db:
    image: 'mysql:8.4.8'
    container_name: mysql_db
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '3306'
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h localhost -u $${MYSQL_USER} -p$${MYSQL_PASSWORD}' ]
      interval: 15s
      timeout: 10s
      retries: 3
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - .env
