services:
  mysql-db:
    image: 'mysql:8.1.0'
    container_name: mysql_db
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
        test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u $${MYSQL_USER} -p$${MYSQL_PASSWORD}']
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s

volumes:
  mysql_data:
    driver: local
